## Data formats

| data_type                           | data_format                                                                                         | description                                                                                  | example_variables                                   | location                |
|-------------|---------------|------------------|----------------|-----------|
| questionnaires                      | tab separated values/comma separated values (.tsv/.csv) accompanied by a JSON (.json) metadata file | all data that can be represented in a table, including numerical, categorical or string data | questionnaires, hormonal data, fMRI behavioral data | on Yoda per wave        |
| physical measures                   | tab separated values (.tsv/.csv) accompanied by a JSON (.json) metadata file                        | hormonal and physical test data represented in a table                                       | testosterone, heart rate                            | on Yoda per wave        |
| anatomical and functional mri scans | NIfTI-1 (.nii) accompanied by a JSON (.json) metadata file                                          | all anatomical and functional scan data represented in a preprocessed format                 | brain activity, cortical thickness                  | on Yoda per participant |
| functional mri behavioral data      | NIfTI-1 (.nii) accompanied by a JSON (.json) metadata file                                          |                                                                                              | reaction time                                       | on Yoda per participant |
|                                     |                                                                                                     |                                                                                              |                                                     |                         |
|                                     |                                                                                                     |                                                                                              |                                                     |                         |
