## Specific naming conventions

As mentioned in the general naming conventions section, naming should be both human as well as machine readable. Most of this can be solved by using BIDS as explained in the previous section, however there are some GUTS-specific naming conventions that need to be adhered to.

**Measure names in file names**

To adhere to the machine-readable condition, file names of measure data should always include `"_task-[]_"`. The short name [(here you can find a list of all measure names)]{.underline} of the measure should be used to ensure each collection site uses the same measure name. For example, the Interpersonal Reactivity Index has short name "`iri`". Its filename will therefore always include `"_task-iri_"`.

**Collection site in names**

##### **Subject IDs**

The subject ID naming convention differs slightly for each of the four data collection sites/working packages. To prevent accidental overlap between collected data between WPs, an abbreviation of the location site will be added to each subject ID, as can been seen below.

As approximately 600 subjects will participate at each location, we advise to use a number between 0 and 600. ~\[Or 0-1000 for loc 1, 1001-2000 for loc 2, etc.\].~ The subject id number should always consists of three numbers, e.g., subject 1 will get the number 001, subject 15 will get the number 015.

| Data collection location          | Subject ID naming convention | Example         |
|-------------------------|------------------------|------------------------|
| Erasmus University Rotterdam      | subguts-eur-#                | subguts-eur-001 |
| Leiden University - Groningen     | subguts-lei-#                | subguts-lei-001 |
| Vrije Universiteit Amsterdam (VU) | subguts-vu-#                 | subguts-vu-001  |
| Universiteit van Amsterdam (UVA)  | subguts-uva-#                | subguts-uva-001 |

##### **File names**

To prevent duplicate file names, each data collection site has to add their abbreviation to the file name. For brain imaging data, the location will be included in the subjectid in the file name, e.g., `subguts-001-eur_ses-02_task-feedback_run-01.nii`. For other data the location needs to be added separately. The file name for the Interpersonal Reactivity Index could, for example, be `loc-lei_task-iri.tsv`~\[or\ without\ the\ loc\]~`.` Here loc stands for 'location' and lei for Leiden University.

**Variables**

We propose the following naming conventions for tabular data. The variable- and value labels can be added to either an SPSS file and later be converted to a .tsv file + .json file, or be manually added to a .json file directly. For more information, about how to make .json files see \[\].

`[session]_[task]_[subpart task]_q/t[question/trial #]`

-   **Names:** lowercase letters with all distinct information separated by an_underscore

-   **Labels:** Full sentences starting with a capital letter.

-   **Value labels:** lowercase letters

| Variable name               | Variable label                                                                                                                                | Value labels                                                    |
|----------------------|----------------------|----------------------------|
| ses-02_iri_pt_q3            | Interpersonal Reactivity Index - Perspective taking scale Q3: I sometimes find it difficult to see things from the other guy's point of view. | 0 = does not describe me very well, 4 = described me very well  |
| ses-02_dailyhassles_freq_q4 | Parenting Daily Hassles scale - Frequency Q4: The kids won't listen or do what they are asked without being nagged.                           | 1 = never, 2 = rarely, 3 = sometimes, 4 = often, 5 = constantly |
| ses-05_pcg_exb1_perc_to2    | Prosocial Cyberball Task - Exclusion Block 1: Percentage of throws to player 2.                                                               |                                                                 |
| ses-05_dd_money_ind_day180  | Delay Discounting Money: Indifference point day 180: Prefer to receive this amount of money now than 10 euros in 180 days.                    |                                                                 |
| ses-02_saliva_cort_d1_m1    | Saliva Samples -Cortisol: Mean cortisol in nmol/l day 1, measurement 1.                                                                       |                                                                 |
